import Phaser from 'phaser';
import { awaitPlayerReady, cloudLoad, cloudSave, gameLoadingReady, initGamePush, trackLevelStart } from '../sdk/gamepush';
import { SaveSystem } from '../systems/SaveSystem';
import { LOGICAL_W, LOGICAL_H } from '../config/dimensions';

export class BootScene extends Phaser.Scene {
  constructor() {
    super('BootScene');
  }

  preload(): void {
    const assetBasePath = this.getAssetBasePath();
    // Animated walk cycles, generated by sprite-sheet-maker (WAN 2.2 i2v).
    // 8 frames @ 256px per character. Names map to chibi static keys above.
    const walkSheets: Array<[string, string]> = [
      ['enemy-knight-walk', 'knight'],
      ['enemy-archer-walk', 'archer'],
      ['enemy-bomber-walk', 'bomber'],
      ['enemy-raider-walk', 'raider'],
      ['enemy-wizard-walk', 'wizard'],
      ['enemy-heavy-knight-walk', 'heavy_knight'],
      ['enemy-log-thrower-walk', 'log_thrower'],
      ['enemy-jumper-walk', 'hammerman']
    ];
    for (const [key, name] of walkSheets) {
      this.load.spritesheet(
        key,
        `${assetBasePath}assets/enemies/${name}_walk_strip.png`,
        { frameWidth: 256, frameHeight: 256 }
      );
    }
    // Knight-only extras: strike1/2 (alternating sword swings), hurt (damage
    // flinch), air_panic (mid-flight loop), getup (after a stunned landing).
    const knightExtras: Array<[string, string]> = [
      ['enemy-knight-strike1', 'knight_strike1'],
      ['enemy-knight-strike2', 'knight_strike2'],
      ['enemy-knight-hurt', 'knight_hurt'],
      ['enemy-knight-air', 'knight_air_panic'],
      ['enemy-knight-getup', 'knight_getup']
    ];
    for (const [key, name] of knightExtras) {
      this.load.spritesheet(
        key,
        `${assetBasePath}assets/enemies/${name}_strip.png`,
        { frameWidth: 256, frameHeight: 256 }
      );
    }
  }

  async create(): Promise<void> {
    const walkAnims = [
      'enemy-knight-walk', 'enemy-archer-walk', 'enemy-bomber-walk',
      'enemy-raider-walk', 'enemy-wizard-walk', 'enemy-heavy-knight-walk',
      'enemy-log-thrower-walk', 'enemy-jumper-walk'
    ];
    // The WAN-generated strips don't always close cleanly between frame 7
    // and the next loop's frame 0 -- there's a visible snap on every cycle.
    // Looping 0..6 hides it; bump back to end:7 once strips are regenerated
    // with seamless-loop prompting.
    const WALK_LAST_FRAME = 6;
    for (const key of walkAnims) {
      if (this.textures.exists(key) && !this.anims.exists(key)) {
        this.anims.create({
          key,
          frames: this.anims.generateFrameNumbers(key, { start: 0, end: WALK_LAST_FRAME }),
          frameRate: 8,
          repeat: -1
        });
      }
    }

    // Knight-only one-shot / loop animations.
    type KnightAnim = { key: string; frameRate: number; repeat: number };
    const knightAnims: KnightAnim[] = [
      { key: 'enemy-knight-strike1', frameRate: 14, repeat: 0 },
      { key: 'enemy-knight-strike2', frameRate: 14, repeat: 0 },
      { key: 'enemy-knight-hurt', frameRate: 14, repeat: 0 },
      { key: 'enemy-knight-air', frameRate: 10, repeat: -1 },
      { key: 'enemy-knight-getup', frameRate: 10, repeat: 0 }
    ];
    for (const { key, frameRate, repeat } of knightAnims) {
      if (this.textures.exists(key) && !this.anims.exists(key)) {
        this.anims.create({
          key,
          frames: this.anims.generateFrameNumbers(key, { start: 0, end: 7 }),
          frameRate,
          repeat
        });
      }
    }

    const width = LOGICAL_W;
    const height = LOGICAL_H;
    this.add.rectangle(width / 2, height / 2, width, height, 0x111827);
    this.add.text(width / 2, height / 2, 'Loading...', {
      color: '#f9fafb',
      fontSize: '28px',
      fontStyle: 'bold'
    }).setOrigin(0.5);

    await initGamePush();
    await awaitPlayerReady();
    await this.mergeCloudSave();
    await gameLoadingReady();

    // GamePush certification: fire LEVEL_START 0 as the "play button clicked"
    // proxy now that the SDK handshake is complete. The per-level LEVEL_START N
    // signal fires inside GameScene.create as the player enters each level.
    trackLevelStart(0);

    // GamePush certification: at least one cloudSave per session counts as a
    // "save observed" telemetry event for the dashboard. Persist the current
    // local save (or defaults on a fresh install) so the indicator goes green
    // on first boot, before the player has finished any level.
    void cloudSave(SaveSystem.load() as unknown as Record<string, unknown>);

    const save = SaveSystem.load();
    this.scene.start(save.currentLevel > 10 ? 'VictoryScene' : 'GameScene');
  }

  // Pull cloud save into localStorage if the SDK has any. localStorage stays
  // the local source of truth - we just hydrate it from the cloud at boot so
  // the rest of the game can keep using SaveSystem synchronously.
  private async mergeCloudSave(): Promise<void> {
    const cloud = await cloudLoad();
    if (!cloud) return;
    SaveSystem.applyCloudData(cloud);
  }

  private getAssetBasePath(): string {
    if (window.location.hostname.endsWith('github.io')) {
      const repoName = window.location.pathname.split('/').filter(Boolean)[0];
      return repoName ? `/${repoName}/` : '/';
    }
    return './';
  }
}
